word: "luge"
alternate_spellings: "looge"
difficulty : MEDIUM
category: THING
complex_textures: "slippery"
complex_ages: "timeless"
materials: "ice"
general_nouns: "olympics"
industry_sectors: "sport"
buildings: "structure"
complex_buildings: "track"
general_adjectives: "aerodynamic"
periods_of_time: "winter"
