word: "luge"
alternate_spellings: "looge"
alternate_spellings: "luge track"
alternate_spellings: "looge track"
difficulty : MEDIUM
category: THING
complex_textures: "slippery"
complex_ages: "timeless"
materials: "ice"
industry_sectors: "sport"
buildings: "structure"
complex_buildings: "track"
general_nouns: "olympics"
general_nouns: "spandex"
general_adjectives: "aerodynamic"
general_adjectives: "fast"
periods_of_time: "winter"
